apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  MYSQL_HOST: ${MYSQL_HOST:-host.minikube.internal}
  MYSQL_USER: ${MYSQL_USER:-auth_user}
  MYSQL_DB: ${MYSQL_DB:-auth}
  MYSQL_PORT: "${MYSQL_PORT:-3306}"