apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
stringData:
  MYSQL_PASSWORD: ${MYSQL_PASSWORD:-auth_password}
  JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
type: Opaque