apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
      tier: backend
  template:
    metadata:
      labels:
        app: order-service
        tier: backend
    spec:
      containers:
      - name: order-api
        image: node:16-alpine
        command: ["node", "-e", "const http = require('http'); const server = http.createServer((req, res) => { res.writeHead(200, {'Content-Type': 'application/json'}); res.end(JSON.stringify({service: 'order-service', orders: [{id: 101, product: 'Laptop', amount: 999}, {id: 102, product: 'Phone', amount: 599}], timestamp: new Date().toISOString()})); }); server.listen(8080, () => console.log('Order service listening on port 8080'));"]
        ports:
        - containerPort: 8080
        env:
        - name: SERVICE_NAME
          value: "order-service"
        - name: PORT
          value: "8080" 