apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-client
spec:
  containers:
  - name: test-client
    image: curlimages/curl:latest
    command: ["sleep", "3600"]
    env:
    - name: USER_SERVICE_URL
      value: "http://user-service:8080"
    - name: ORDER_SERVICE_URL
      value: "http://order-service:8080" 