apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: microservices
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword123"
  MYSQL_DATABASE: "auth"
  MYSQL_USER: "auth_user"
  MYSQL_PASSWORD: "auth_password123"
