apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: auth-secrets
  namespace: microservices
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/video-converter-469811/secrets/mysql-password/versions/latest"
        path: "mysql-password"
      - resourceName: "projects/video-converter-469811/secrets/jwt-secret/versions/latest"
        path: "jwt-secret"
      - resourceName: "projects/video-converter-469811/secrets/mysql-root-password/versions/latest"
        path: "mysql-root-password"
      - resourceName: "projects/video-converter-469811/secrets/mysql-database/versions/latest"
        path: "mysql-database"
      - resourceName: "projects/video-converter-469811/secrets/mysql-user/versions/latest"
        path: "mysql-user"
  secretObjects:
  - secretName: auth-secret
    type: Opaque
    data:
    - objectName: "mysql-password"
      key: "MYSQL_PASSWORD"
    - objectName: "jwt-secret"
      key: "JWT_SECRET"
  - secretName: mysql-secret
    type: Opaque
    data:
    - objectName: "mysql-root-password"
      key: "MYSQL_ROOT_PASSWORD"
    - objectName: "mysql-password"
      key: "MYSQL_PASSWORD"
    - objectName: "mysql-database"
      key: "MYSQL_DATABASE"
    - objectName: "mysql-user"
      key: "MYSQL_USER"
