apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-account
  namespace: microservices
  annotations:
    iam.gke.io/gcp-service-account: auth-secrets-sa@video-converter-469811.iam.gserviceaccount.com
