apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: microservices
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
